### ISSUE TITLE
Just hangs in 0% with this dataset

### ISSUE THREAD

**Issue by jaakla** [austromorph/cartogram3#21]
Is something wrong with the data? Too big?

Cartogram either hangs in 0% or crashes immediately QGIS (tested with 3.13 and 3.14 on mac). With the bundled sample data on same QGIS cartogram works fine.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/5609650/86478302-be8b7580-bd52-11ea-9b0c-b8d8781e99f4.png">

[Archive.zip](https://github.com/austromorph/cartogram3/files/4870180/Archive.zip)

**Comment by christophfink** [comment]
It’s “simply” a performance issue. The algorithm ([Dougenik et al. 1985](http://www.tandfonline.com/doi/abs/10.1111/j.0033-0124.1985.00075.x)) scales very badly – it loops over every point times every polygon. 
Your data set is quite detailed (1163486 points in 79 polygons). On my computer (QGIS 3.14 on Arch Linux on an aging Thinkpad) it does compute, but very slowly (Note that also the progress bar is not 100% linear, but always “pauses” at the end of each iteration when it uses one core only for computing residual errors).

I simplified your data set (see attached file, it’s down to 12901 points in 79 polygons); with that one it works really fast. Tallinn blows up like a balloon, and Hiiumaa shrinks stronger than I would have thought :-D

Since the map is going to be distorted anyway, some loss of details is acceptable, IMHO, but I might have simplified it too much for your taste. You can of course process the detailed data set, but it might take very long.

![elanikearv](https://user-images.githubusercontent.com/4998473/86489934-724e2e80-bd6e-11ea-8ff1-32700dd32b89.png)

[estonia_omavalitsus_20200701.gpkg.zip](https://github.com/austromorph/cartogram3/files/4870859/estonia_omavalitsus_20200701.gpkg.zip)

**Comment by christophfink** [comment]
I used [these instructions](http://strk.kbt.io/blog/2012/04/13/simplifying-a-map-layer-using-postgis-topology/) to simplify the dataset while retaining topology, using PostGIS. Correct topology is not necessary for the Dougenik et al. algorithm, so you can basically use any Douglas-Peucker implementation (such as the one built-in to QGIS). I also recommend discarding all the small islands below a certain threshold (I used 100 000 m²) since they cannot be reasonably simplified and amount to a large number of points.

**Comment by jaakla** [comment]
Thanks! As it did not seem to consume also any CPU, and tried to show some message then I was not considering performance thing.

I also just completed basically same steps, just using [topojson CLI tools instructions](https://medium.com/@mbostock/command-line-cartography-part-3-1158e4c55a1e) instead of PostGIS, as this gives a bit better control over memory consumption. And it worked fine with similar result. I suspected simple DP would end up with ugly holes between polygons, whatever you do with that afterwards, better be safe than sorry :).
